name: Passky
version: ${project.version}
main: com.rabbitcomapny.Passky
api-version: 1.13
authors: [ RabbitCompany,sandtechnology ]
description: The best authentication plugin
commands:
  login:
    usage: /<command>
    aliases: [ log, l ]
    description: Login to your minecraft account.
  logout:
    usage: /<command>
    description: Log out of your Minecraft account.
  register:
    usage: /<command>
    aliases: [ reg, r ]
    description: Register a new Minecraft account.
  changepassword:
    usage: /<command>
    aliases: [ changepass, cp ]
    description: Change your current Minecraft account password.
  forcechangepassword:
    usage: /<command>
    aliases: [ forcechangepass, fcp, fp ]
    permission: passky.forcechangepassword
    description: Force a password change for another player's account.
  forceregister:
    usage: /<command>
    aliases: [ forcereg, fr ]
    permission: passky.forceregister
    description: Register an account for another player.
  forcelogin:
    usage: /<command>
    aliases: [ forcelog, fl ]
    permission: passky.forcelogin
    description: Force log in a player without requiring a password.
permissions:
  passky.forcechangepassword:
    default: op
    description: Allow to use forcechangepassword command
  passky.forceregister:
    default: op
    description: Allow to use forceregister command